/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
    maven("https://repository.jboss.org/nexus/content/groups/public-jboss")
    maven("https://repository.jboss.org/nexus/content/repositories")
    maven("https://repository.jboss.org/nexus/content/repositories/thirdparty-releases")
    maven {
        url = uri("http://sankhyatec.mgcloud.net.br/api/v4/projects/173/packages/maven")
        isAllowInsecureProtocol =  true
        name = "GitLab"
        metadataSources {
            artifact()
            mavenPom()
        }
        credentials(HttpHeaderCredentials::class.java) {
            name = "Private-Token"
            value = "YzDkSQZrWVnXYzG1RMQN"
        }
        authentication {
            create<HttpHeaderAuthentication>("header")
        }
    }

    flatDir {
        dirs("lib")
    }
}

dependencies {
    implementation("br.com.sankhya.extensions:snkwext:1.0")
    implementation("br.com.sankhya.jape:snkjape:1.0")
    implementation("br.com.sankhya.mgecomercial:snkmgecommodel:1.0")
    implementation("br.com.sankhya.modelcore:snkmodelcore:1.0")
    implementation("br.com.sankhya.util:sanutil:1.0")
    implementation("br.com.sankhya.monitor:lughlib:4.0.5")
    implementation("com.google.code.gson:gson:2.8.5")
    implementation("org.json:json:20190722")
    implementation("br.com.sankhya.sanws:sanws:4.5b198")
    implementation("javax.servlet:servlet-api:2.5")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
}

group = "br.com.goup.snkintegrations"
version = "1.0.31-SNAPSHOT"
description = "Sankhya Custom Events Programmer"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
